steps:
  - name: 'gcr.io/$PROJECT_ID/openjdk-11-lein-slim-buster'
    entrypoint: 'bash'
    args:
     - -c
     - CLOJARS_TOKEN="$$CLOJARS_TOKEN" lein deploy clojars
    env:
      - 'CLOJARS_USERNAME=lupapiste'
    secretEnv:
      - CLOJARS_TOKEN

availableSecrets:
  secretManager:
    - versionName: projects/686311695231/secrets/clojars-deploy-token/versions/1
      env: 'CLOJARS_TOKEN'
